spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UMC?serverTimezone=Asia/Seoul&characterEncoding=UTF-8?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: 924498
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
