spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UMC?serverTimezone=Asia/Seoul&characterEncoding=UTF-8?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    password: 924498
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.type.descriptor.sql: trace # 파라미터 값 출력

cloud:
  aws:
    s3:
      bucket: myumcbucket
      path:
        review: reviews
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
